/**
 * Codegen: embed the capability-routing Pi extension source into a TypeScript
 * module so phantombot's compiled single-ELF binary can stamp it onto disk at
 * runtime (see src/lib/piExtensionProvision.ts).
 *
 * Why a generated constants module (vs. `import ... with { type: "text" }`)?
 * The text-import form is NOT tsc-safe in this toolchain — `tsc --noEmit`
 * rejects it. Generating a plain `.ts` with the file contents as JSON-encoded
 * string literals sidesteps that entirely and keeps `bun build --compile`
 * self-contained (no runtime fs read of the repo, which won't exist in the
 * shipped binary).
 *
 * Run: `bun run gen:pi-extension` (regenerate whenever the extension changes;
 * tests/lib-piExtensionAssets.test.ts fails CI if the checked-in module drifts).
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const EXT_DIR = join(REPO_ROOT, "pi-extension", "capability-routing");
const OUT_FILE = join(REPO_ROOT, "src", "lib", "piExtensionAssets.generated.ts");

/** Relative paths (keys) of the files embedded in the binary. */
const FILES = [
  "index.ts",
  "tools.ts",
  "spawnPi.ts",
  "README.md",
  "agents/coder.md",
] as const;

function hashEntries(entries: Array<[string, string]>): string {
  const h = createHash("sha256");
  for (const [rel, content] of [...entries].sort((a, b) => a[0].localeCompare(b[0]))) {
    h.update(rel, "utf8");
    h.update("\0", "utf8");
    h.update(content, "utf8");
    h.update("\0", "utf8");
  }
  return h.digest("hex");
}

const entries: Array<[string, string]> = FILES.map((rel) => [
  rel,
  readFileSync(join(EXT_DIR, rel), "utf8"),
]);

const hash = hashEntries(entries);

const body = [
  "// GENERATED by scripts/genPiExtensionAssets.ts — DO NOT EDIT. Run: bun run gen:pi-extension",
  "//",
  "// Embeds the pi-extension/capability-routing/ source so phantombot's compiled",
  "// binary can stamp it into ~/.pi/agent/extensions/ at startup.",
  "",
  "export const PI_EXTENSION_FILES: Record<string, string> = {",
  ...entries.map(
    ([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`,
  ),
  "};",
  "",
  `export const PI_EXTENSION_ASSETS_HASH = ${JSON.stringify(hash)};`,
  "",
].join("\n");

writeFileSync(OUT_FILE, body, "utf8");
// eslint-disable-next-line no-console
console.log(
  `wrote ${OUT_FILE} (${entries.length} files, hash ${hash.slice(0, 12)}…)`,
);
